blank_issues_enabled: false
contact_links:
  - name: Urgent / Emergency
    url: mailto:h.baker@hertie-school.org
    about: For urgent issues affecting your ability to work, email directly instead of opening an issue.
